print('==Caulculo de almento de salário!==')
nome = input('Nome:')
sal = float(input('Salário do funcionário:'))
print(f'Funcionário = {nome}')
print(f'Salário de R${sal:.2f}')
alm = float(input('Digite o valor da porcentagem de almento:'))
total = sal + (sal * alm/100)
print('O salário atual do funcionario(a) {} , é de R${:.2f} '.format(nome,sal))
print(f'Com o almento de {alm:.0f}% , o salario do funcionário {nome} ficará R${total:.2f} !')
