print('==Caulculo de almento de salário!==')
nome = input('Nome:')
sal = float(input('Salário do funcionário:'))
print('Funcionário = {}'.format(nome))
print('Salário de R${:.2f}'.format(sal))
alm = float(input('Digite o valor da porcentagem de almento:'))
total = sal + (sal * alm/100)
print('O salário atual do funcionario(a) {} , é de R${:.2f} '.format(nome,sal))
print('Com o almento de {:.0f}% , o salario do funcionário {} ficará R${:.2f} !'.format(alm,nome,total))
